import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../styles/globals.scss";

const openSans = Open_Sans({
  weight: ["300", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${openSans.className || ""} background-color`}>
        {children}
      </body>
    </html>
  );
}
